
# 应用实例操作
endpoints:
  shutdown:
    enabled: true # 启用shutdown
    sensitive: true # 密码验证
  restart:
    enabled: true # 启用restart
    sensitive: true
  logfile:
    enabled: true # /logfile访问日志文件

management:
  security:
    enabled: false

swagger:
  enable: true

# 日志
logging:
  path: D:/Work/log/
  config: classpath:logback.xml

# 将服务注册到eureka
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:6688/eureka/ # eureka注册路径

spring:
  mvc:
    favicon:
      enabled: false

# SpringCloud 服务追踪
#  zipkin:
#    enabled: true
#    base-url: http://localhost:8888/

# SpringMVC JSON格式转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 响应json字符串，对日期格式的格式化
    time-zone: GMT+8 # 东八区，北京时间
    default-property-inclusion: non_null # 忽略null值

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    pool:
      max-idle: 100 #连接池中的最大空闲连接
      min-idle: 1 #连接池中的最小空闲连接
      max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      timeout: 0 #连接超时时间（毫秒）

# Spring 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/node
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
#    schema: database/import.sql # 启动应用时需要导入的SQL脚步
#    sql-script-encoding: utf-8 # 脚步的编码

# 阿里Druid
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 10
      minIdle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.json,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        #allow: 127.0.0.1,192.168.16.110 # IP白名单
        #deny: 192.168.16.111 # IP黑名单
