
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10000
    #lease-renewal-interval-in-seconds: 10000 # 续约更新时间间隔（默认30秒）
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port:6666}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000

management:
  security:
    enabled: false
