
server:
  port: 2222 # 端口

spring:
  application:
    name: gzedu-server-config # 应用名称
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties/
#        git:
#          uri: https://github.com/mortalliao/springcloud-demo.git
#          search-paths: gzedu-springcloud/learnshop-config

#spring.cloud.config.server.git.username=username
#spring.cloud.config.server.git.password=password

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
  client:
    lease:
      duration: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

management:
  security:
    enabled: false
