
gate:
  ignore:
    startWith: /static,/auth/jwt

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
  client:
    lease:
      duration: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:6688/eureka/

zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  add-proxy-headers: true
  routes:
    sso:
      path: /sso/**
      sensitiveHeaders: "*"
      serviceId: easycloud-admin

    api-portal:
      path: /manage/**
      sensitiveHeaders: "*"
      serviceId: easycloud-manage

#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

management:
  security:
    enabled: false
