
endpoints:
  logfile:
    enabled: false

logging:
  path: /log/ecloud-XXX/ecloud-XXX
  config: classpath:logback.xml

swagger:
  enabled: false

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:6688/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 1000 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

spring:
  datasource:
    #schema: classpath:/database/ecloud-test-scheme.sql
    #data: classpath:/database/ecloud-test-data.sql
    url: jdbc:mysql://localhost:3306/node
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
