
#logging:
#  path: /log/ecloud-manage
#  config: classpath:logback.xml

endpoints:
  logfile:
    enabled: false

management:
  security:
    enabled: false

swagger:
  enable: true

logging:
  path: /log/easycloud-micro-services/easycloud-jwt
  config: classpath:logback.xml

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
  client:
    lease:
      duration: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:6688/eureka/

spring:
  mvc:
     favicon:
       enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  datasource:
    #data: classpath:/database/ecloud-integral-data.sql
    url: jdbc:oracle:thin:@172.16.146.66:1521:gzdec
    username: DC_OPEN_TEACHER_YX
    password: password
    driverClassName: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: oracle

    druid:
      # 初始化大小，最小，最大
      initial-size: 10
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true

      web-stat-filter:
        enable: true
        url-pattern: /*
        exclusions: "*.js,*.json,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        allow: 127.0.0.1 # IP白名单
        deny:  # IP黑名单

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.ecloud.wlyx.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #逻辑删除配置
    logic-delete-value: Y
    logic-not-delete-value: N
    #自定义填充策略接口实现
    #meta-object-handler: com.ecloud.integral.config.mybatisplus.CommonMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

