
logging:
  path: /log/ecloud-manage
  config: classpath:logback.xml

endpoints:
  logfile:
    enabled: true

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://172.16.146.184:6688/eureka/

spring:
  mvc:
    favicon:
      enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

security:
  ignored: /favicon.ico,/js/**,/css/**,/layui/**
  sessions: always
  oauth2:
    sso.login-path: /login
    resource.jwt.key-uri: http://172.16.146.184:8084/oauth/token_key
    client:
      client-id: ssoclient
      client-secret: ssosecret
      access-token-uri: http://172.16.146.184:8084/oauth/token
      user-authorization-uri: http://172.16.146.184:8084/oauth/authorize
      client-authentication-scheme: form
